### PR TITLE
Remove Feature

### PR DESCRIPTION
**Pull request by mgray35**
Implements remove method

### CODE REVIEW

**Comment by mgray35** [comment]
Est. time: < 1 hr

**Comment by kevinkoos** [comment]
Take a look at the conditional in the remove function again. I think you meant to call the colunmHasCards function you also completed. colunmHasCards looks good.

**Comment by mgray35** [comment]
I actually thought I took columnHasCards out, which is why I wrote remove like that. Updated now to make use of columnHasCards

**Comment by kevinkoos** [comment]
Looks great now.

**Pull request merged**
