### PR TITLE
Tabbed and cleaned up move and columns

### PR DESCRIPTION
**Pull request by osugraytr**
Changes:
    tabbed out everything to line up
    changed columns and rows to look nicer

### CODE REVIEW

**Comment by osugraytr** [comment]
The idea for tabbing the css was so the Html was a little easier to edit.

**Comment by mgray35** [comment]
I went ahead and implemented the suggested section

**Comment by osugraytr** [comment]
I got rid of the old Java code that has a merge conflict. Could someone review this to make sure it works?

**Comment by osugraytr** [comment]
I closed this

**Pull request closed without merging**
